server:
  port: 8097

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9090
      group-id: orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderPlacedEvent:com.online.store.application.kafka.dto.OrderPlacedEvent
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification-ecommerce-app
  datasource:
    url: jdbc:postgresql://localhost:5431/notifications-ecommerce-app
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect